insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('C002', '!', 'Escherichia coli (E.coli)', 0, 'No. 100/ml')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('C003', '!', 'Enterococci (Confirmed) ', 0, 'No. 100/ml')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('C002B', '!', 'Escherichia coli (E.coli-bottles or containers)', 0, 'No. 250/ml')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('C003B', '!', 'Enterococci (Bottles or containers) ', 0, 'No. 250/ml')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('C005', '!', 'Pseudomonas aeruginosa (Bottles or containers) ', 0, 'No.250/ml')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('C007', '!', 'Colony Counts 3 days @ 22°C (Bottles or containers) ', 100, 'No. /ml')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('C013', '!', 'Colony Counts 37°C (Bottles or containers) ', 20, 'No. /ml')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('F008', '!', 'Acrylamide', 0.1, 'ug/l')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('B008A', '!', 'Antimony', 5, 'ug/l')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('B001A', '!', 'Arsenic (Total)', 10, 'ug/l/AS')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('F002', '!', 'Benzene (Total)', 1, 'ug/l ')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('D007', '!', 'Benzo[a]Pyrene (Total)', 0.01, 'ug/l ')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('D005A', '!', 'Boron', 1, 'mg/l B')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('F003', '!', 'Bromate', 10, 'ug/l BrO3')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('B002', '!', 'Cadmium (Total)', 5, 'ug/l  Cd')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('B004', '!', 'Chromium (Total)', 50, 'ug/l  Cr')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('A024A', '!', 'Copper (Total)', 2, 'mg/l Cu')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('B003', '!', 'Cyanide (Total)', 50, 'ug/l  CN')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('F001', '!', '1 2-Dichloroethane (Total)', 3, 'ug/l ')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('F010', '!', 'Epichlorohydrin', 0.1, 'ug/l (Product Spec)')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('A027', '!', 'Fluoride (Total)', 1.5, 'mg/l F')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('B007A', '!', 'Lead (Total - 25)', 25, 'ug/l  Pb')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('B007B', '!', 'Lead (10 - will apply 25.12.2013)', 10, 'ug/l  Pb')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('B005', '!', 'Mercury (Total)', 1, 'ug/l  Hg')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('B006A', '!', 'Nickel (Total)', 20, 'ug/l  Ni')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('A012', '!', 'Nitrate', 50, 'mg/l  NO3')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('A013A', '!', 'Nitrite - Consumers Taps', 0.5, 'mg/l  NO2')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('A013B', '!', 'Nitrite - Treatment Works', 0.1, 'mg/l  NO2')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('A013C', '!', 'Nitrite/Nitrate formula', 1, 'mg/l')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('P002', '!', 'Aldrin', 0.03, 'ug/l ')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('P028', '!', 'Dieldrin (Total) ', 0.03, 'ug/l ')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('P043', '!', 'Heptachlor (Total)', 0.03, 'ug/l ')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('P044', '!', 'Heptachlor Epoxide - Total', 0.03, 'ug/l ')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('P000', '!', 'Other Pesticides', 0.1, 'ug/l ')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('B010', '!', 'Pesticides (Total by Calculation)', 0.5, 'ug/l ')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('B011F', '!', 'Polycyclic Aromatic Hydrocarbons (Total by Calculation)', 0.1, 'ug/l ')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('B009', '!', 'Selenium (Total)', 10, 'ug/l  Se')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('D009B', '!', 'Trichloroethene & Tetrachloroethene - Sum Of 2 Substances (Total by Calculation)', 10, 'ug/l ')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('D011', '!', 'Trihalomethanes (Total by Calculation)', 100, 'ug/l ')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('F009', '!', 'Vinyl Chloride', 0.5, 'ug/l (Product Spec)')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('A021', '!', 'Aluminium (Total)', 200, 'ug/l Al')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('A001', '!', 'Colour', 20, 'mg/l Pt/Co')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('A022', '!', 'Iron (Total)', 200, 'ug/l  Fe')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('A023', '!', 'Manganese (Total)', 50, 'ug/l  Mn')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('A003', '!', 'Odour', NULL, 'No.')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('A009', '!', 'Sodium (Total)', 200, 'mg/l Na')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('A004', '!', 'Taste (Taste Quant)', NULL, 'No.')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('D008', '!', 'Tetrachloromethane (Total)', 3, 'ug/l ')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('A002', '!', 'Turbidity', 4, 'NTU')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('A014', '!', 'Ammonium (Total)', 0.5, 'mg/l  NH4')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('D002A', '!', 'Chloride', 250, 'mg/l C')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('C004A', '!', 'Clostridium perfringens (including spores)', 0, 'No. 100/ml')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('C001A', '!', 'Coliform Bacteria (Indicator)', 0, 'No. 100/ml')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('C007', '!', 'Colony Counts 22°C (Indicator)', NULL, 'Count ')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('C013', '!', 'Colony Counts 37°C (Indicator)', NULL, 'Count ')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('D001', '!', 'Conductivity (Electrical Conductivity)', 2500, 'uS/cm @ 20°C')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('A006', '!', 'Hydrogen ion (pH) - Indicator (Hydrogen ion) (Ph)', NULL, 'PH value')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('A007', '!', 'Sulphate', 250, 'mg/l  SO4')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('F007', '!', 'Total indicative dose (for radioactivity)', 0.1, 'mSv/year')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('A017', '!', 'Total Organic Carbon', NULL, 'mg/l C')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('F006', '!', 'Tritium', 100, 'Bq/l')
insert into ehpwtest (pwtestkey, u_version, pwtestdesc, pwtestpcx, pwtestunits) values ('A002A', '!', 'Turbidity - Indicator', 1, 'NTU')
go
